-- ============================================================
-- Mawsim — S2: public read of farmer PUBLIC profile fields
-- ============================================================
-- The marketplace is public: active listings (and RFQ match results) must show
-- the producer's farm name, region, and rating so buyers can judge a counterpart
-- (CLAUDE.md UX §2 "farmer dignity", §6, S2-04 DoD "farmer info"). The Sprint 1
-- `farmer_profiles_select` policy only exposed a profile to its owner/admin,
-- which made public listing detail + buyer RFQ matching return no farmer info.
--
-- RLS is row-level, so this permissive SELECT policy is OR'd with the existing
-- owner/admin one, making farmer_profiles rows readable by anyone.
--
-- SECURITY (CLAUDE.md §11.1 — bank details farmer+admin only, audit-logged):
--   * `bank_details_encrypted` is ENCRYPTED AT REST; row visibility of ciphertext
--     does not leak plaintext. It is unused until Sprint 4 (currently always NULL).
--   * Marketplace/public queries select ONLY public columns and never this one.
--   * Decryption stays gated to a farmer/admin server action that access-audits.
--   * Sprint 4 HARDENING: when bank details gain a write path, relocate them to a
--     dedicated `farmer_bank_details` table with strict farmer+admin RLS rather
--     than a column on this now-public table. See payments-engineer handoff.
CREATE POLICY farmer_profiles_public_select ON farmer_profiles
  FOR SELECT USING (true);
